# Generated by Django 3.1.7 on 2021-04-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('weight', models.FloatField(max_length=5)),
                ('height', models.FloatField(max_length=5)),
                ('muscle', models.FloatField(max_length=5)),
                ('fat', models.FloatField(max_length=5)),
            ],
        ),
    ]
