# Generated by Django 3.1.7 on 2021-04-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('item_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.board')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('study_exp', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('character_type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('exp', models.FloatField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('study_id', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.study')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='study',
            name='user_id',
            field=models.ForeignKey(db_column='host_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='study_id',
            field=models.ForeignKey(db_column='from', on_delete=django.db.models.deletion.CASCADE, to='helpapp.study'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user_id',
            field=models.ForeignKey(db_column='to', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
        migrations.AddConstraint(
            model_name='user_study',
            constraint=models.UniqueConstraint(fields=('user_id', 'study_id'), name='user_in_study'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('user_id', 'item_id'), name='item_in_inventory'),
        ),
    ]
