# Generated by Django 3.0.3 on 2021-05-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_auto_20210509_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='name',
            new_name='study_name',
        ),
    ]
