# Generated by Django 3.1.7 on 2021-04-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_auto_20210404_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.IntegerField(primary_key=django.db.models.deletion.CASCADE, serialize=False)),
                ('study_exp', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('character_type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('exp', models.FloatField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpapp.study')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='study',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpapp.user'),
        ),
    ]
