# Generated by Django 3.1.7 on 2021-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_auto_20210418_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
