# Generated by Django 3.1.7 on 2021-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0003_auto_20210418_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exp',
        ),
        migrations.AddField(
            model_name='user',
            name='arm_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='back_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='belly_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='chest_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='leg_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='shoulder_exp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='character_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_study',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
