# Generated by Django 3.1.7 on 2021-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0004_auto_20210511_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
